spring:
  profiles:
    include: oauth2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/farmily_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  mvc:
    converters:
      preferred-json-mapper: gson

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true