spring:
  profiles:
    include:
    - oauth2
    group:
      local:
        - db-local
        - file-server-local
        - oauth2-local
      dev:
        - db-dev
        - file-server-dev
        - oauth2-dev
server:
  servlet:
    encoding:
      charset: "UTF-8"
      enabled: true
      force: true