spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
          kakao:
            client-id: 3577be51ad74062922250c5b9b15f3b0
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_image, profile_nickname, openid
        provider:
          # id token에는 id claim이 포함되어있지 않다.
          # https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token-response-id-token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            user-name-attribute: sub

            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json